"""auto update

Revision ID: 011bab43acbd
Revises: 9f2e6ca80687
Create Date: 2026-05-19 14:29:42.582022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011bab43acbd'
down_revision: Union[str, Sequence[str], None] = '9f2e6ca80687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('score_values', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_templates_id'), 'scoring_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_templates_id'), table_name='scoring_templates')
    op.drop_table('scoring_templates')
    # ### end Alembic commands ###