"""auto update

Revision ID: 07d3a4128b41
Revises: add_start_time_col
Create Date: 2026-05-23 20:27:39.954717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d3a4128b41'
down_revision: Union[str, Sequence[str], None] = 'add_start_time_col'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archer_groups', sa.Column('visibility', sa.String(), nullable=True))
    op.add_column('archer_groups', sa.Column('invite_code', sa.String(), nullable=True))
    op.drop_index(op.f('uq_replay_videos_target'), table_name='replay_videos')
    op.add_column('tournaments', sa.Column('max_group_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'max_group_size')
    op.create_index(op.f('uq_replay_videos_target'), 'replay_videos', ['tournament_id', 'archer_id', 'course_number', 'target_number'], unique=True)
    op.drop_column('archer_groups', 'invite_code')
    op.drop_column('archer_groups', 'visibility')
    # ### end Alembic commands ###