"""auto update

Revision ID: 52fb640eff61
Revises: 810ad8cd1efb
Create Date: 2026-05-22 18:53:53.850081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fb640eff61'
down_revision: Union[str, Sequence[str], None] = '810ad8cd1efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('scoring_template_id', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('course_map_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'course_map_url')
    op.drop_column('tournaments', 'scoring_template_id')
    # ### end Alembic commands ###