"""auto update

Revision ID: 57dc23b608e5
Revises: 1d5a730d4ed4
Create Date: 2026-05-14 14:47:16.245942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57dc23b608e5'
down_revision: Union[str, Sequence[str], None] = '1d5a730d4ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('course_number', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('courses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'courses')
    op.drop_column('scores', 'course_number')
    # ### end Alembic commands ###