"""auto update

Revision ID: 9d07de0520ad
Revises: e817acb242d8
Create Date: 2026-05-14 15:52:59.470752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d07de0520ad'
down_revision: Union[str, Sequence[str], None] = 'e817acb242d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'archer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scores', 'target_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scores', 'score_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tournament_archers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('tournament_archers', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('tournament_archers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('tournament_archers', sa.Column('purchased_mulligans', sa.String(), nullable=True))
    op.alter_column('tournament_archers', 'archer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tournament_archers', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tournaments', sa.Column('mulligans', sa.String(), nullable=True))
    op.alter_column('tournaments', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tournaments', 'num_targets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tournaments', 'num_targets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tournaments', 'mulligans')
    op.alter_column('tournament_archers', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tournament_archers', 'archer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tournament_archers', 'purchased_mulligans')
    op.drop_column('tournament_archers', 'phone')
    op.drop_column('tournament_archers', 'last_name')
    op.drop_column('tournament_archers', 'first_name')
    op.alter_column('scores', 'score_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scores', 'target_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scores', 'archer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###