"""auto update

Revision ID: 9f2e6ca80687
Revises: d27d0ea65e33
Create Date: 2026-05-18 15:36:21.454472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2e6ca80687'
down_revision: Union[str, Sequence[str], None] = 'd27d0ea65e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('archer_id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('target_number', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(), server_default='public', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_videos_id'), 'replay_videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replay_videos_id'), table_name='replay_videos')
    op.drop_table('replay_videos')
    # ### end Alembic commands ###