"""auto update

Revision ID: cad821a735ed
Revises: b9c6f0e9f48b
Create Date: 2026-05-22 13:27:48.843723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad821a735ed'
down_revision: Union[str, Sequence[str], None] = 'b9c6f0e9f48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archer_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('shooting_order_mode', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archer_groups_id'), 'archer_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archer_groups_id'), table_name='archer_groups')
    op.drop_table('archer_groups')
    # ### end Alembic commands ###