"""auto update

Revision ID: d1dd598018b2
Revises: 4737d4b30808
Create Date: 2026-05-19 22:57:52.542842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dd598018b2'
down_revision: Union[str, Sequence[str], None] = '4737d4b30808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_templates', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_templates', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###